---
- hosts: all
  become: true
  tasks:
    - name: install docker
      command: sh get-docker.sh

    - name: check docker is active
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure group "docker" exists
      group:
        name: docker

    - name: adding ubuntu to docker group
      user:
        name: vagrant
        groups: docker

    - name: starting docker compose
      command: docker-compose -f docker-compose.yml up -d
